### ISSUE TITLE
DIscontinuous unit as antecedent of discourse deixis breaks visualization

### ISSUE THREAD

**Issue by poesio** [nlpAThits/MMAX2#2]
Same set of documents as in previous issue - in document 0669, the antecedent of  discourse-deictic 'that' (word_213) is a discontinuous unit 236, consisting of ["By the end of the 1990s,"] he said, [we want to be producing ...] - but this seems to break the visualization, the red arrow we use to visualize discourse deixis now points to the beginning of the doc
![Screen Shot 2020-12-03 at 18 17 49](https://user-images.githubusercontent.com/25485819/101071314-57d5e680-3594-11eb-8494-cb4c93493d16.png)

**Comment by hits-nlp** [comment]
Fixed with Version 1.14, which will be made publicly available soon.
